[package]
name = "simple_web_server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0" 

# actix-web은 비동기 런타임으로 tokio를 사용하므로 추가
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }